### PR TITLE
Upadate with user journeys

### PR DESCRIPTION
**Pull request by lauportell**
Upadate with user journeys

### CODE REVIEW

**Review by marina-popleteeva — COMMENTED** [review]
Hi @lauportell ,
Thank you for putting user journeys into markdown.
You added 6 pictures but there is no links for them in the text. Is it intended to be? 

Could you also add your name and institute into list of authors?

**Comment by lauportell** [comment]
Yes, I wanted to add them but didn't know how to do it.
I was going to look into it but didn't have time yet.
I will add my name in the authors list :)

**Comment by marina-popleteeva** [comment]
I added images, hopefully in the right format :) (they looks good on GitHub preview), and requested a merge to your branch.

**Comment by lauportell** [comment]
Thank you Marina!
Looks good to me :)

**Pull request merged**
